title:        imagettftextgradient
name:         imagettftextgradient
description:  imagettftextgradient is a drop in replacement for imagettftext with added parameters to add gradient, glow and shadow effects to your PHP GD images.
author:       Andrew G. Johnson
author_email: andrew@andrewgjohnson.com
email:        andrew@andrewgjohnson.com
url:          "https://imagettftextgradient.agjgd.org"
includes_dir: .
layouts_dir:  documentation/imagettftextgradient.agjgd.org/layouts
exclude:      [
               .github,
               .github/*.md,
               .github/*.yml,
               .github/CODEOWNERS,
               .github/ISSUE_TEMPLATE,
               .github/ISSUE_TEMPLATE/*.yml,
               CHANGELOG.md,
               CNAME,
               composer.json,
               documentation/README.md,
               examples/*.php,
               examples/*.ttf,
               LICENSE,
               README.md,
               source
              ]
